# Generated by Django 3.2.3 on 2021-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True)),
                ('category', models.CharField(choices=[('W', 'Weapons'), ('D', 'Dresses'), ('F', 'Furniture'), ('Fo', 'Food')], max_length=2)),
            ],
        ),
    ]
