# Generated by Django 3.2.3 on 2021-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jag', '0004_auto_20210520_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='canvas_pics'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothing_pics'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='laptop_pics'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='painting_pics'),
        ),
    ]
