# Generated by Django 3.2.3 on 2021-05-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jag', '0003_auto_20210520_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothings',
            new_name='Clothing',
        ),
        migrations.RenameModel(
            old_name='Laptops',
            new_name='Laptop',
        ),
        migrations.RenameModel(
            old_name='Mobiles',
            new_name='Mobile',
        ),
        migrations.RenameModel(
            old_name='Paintings',
            new_name='Painting',
        ),
    ]
