# Generated by Django 3.2.3 on 2021-05-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jag', '0005_auto_20210520_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
